### ISSUE TITLE
Custom animation example is missing

### ISSUE THREAD

**Issue by vptcnt** [watery-desert/swipeable_tile#1]
Hello,

Is it possible to put the code for the custom animation shown on the screenshot ?

Thanks

**Comment by watery-desert** [comment]
which screenshot?

**Comment by vptcnt** [comment]
On the main page, you have a animated gif with différent screens 

![screenshot](https://raw.githubusercontent.com/watery-desert/assets/main/swipeable_tile/demo_recording.gif)

The first screen is normal swipeable tile 
The second is swipeable cards
**The third is with a custom animation**
The fourth is with chat bubbles

Do you have the source code for the third screen ?

**Comment by watery-desert** [comment]
I told you in the email I lost it. However, after that, I looked in my folders and I found it. It's easy to implement, it's done using custom paint. The implementation is somehow similar [to this code](https://github.com/watery-desert/water_drop_nav_bar)

If you really want to get this animation code you have to pay me, I will give you.
