### ISSUE TITLE
How remove vertical dividers after swipe?

### ISSUE THREAD

**Issue by samatzhusup** [watery-desert/swipeable_tile#4]
Hi!
How can I remove these?

![2022-06-26_00-11-21](https://user-images.githubusercontent.com/50781959/175789186-70d2c3c1-a05a-4552-bba4-1aa9d85c444a.png)

https://user-images.githubusercontent.com/50781959/175789120-a362e7c0-2268-4b33-8fb0-867b33431f78.mp4

**Comment by watery-desert** [comment]
There is no divider. Set ` isElevated: false,` to remove shadow.

**Comment by watery-desert** [comment]
closing because of no reply.
